import { createServer } from 'node:http';
import { spawn } from 'node:child_process';
import { mkdir, readFile, writeFile, readdir, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve, relative } from 'node:path';
import crypto from 'node:crypto';
import WebSocket from 'ws';
const PORT=Number(process.env.PORT||8787),HOST=process.env.HOST||'0.0.0.0',DATA=process.env.DATA_DIR||'/data',API_TOKEN=process.env.CONNECTOR_API_TOKEN||'',TN_API_URL=process.env.TRUENAS_API_URL||'https://192.168.220.101/api/v2.0';
const historyFile=join(DATA,'history.json'),conflictsFile=join(DATA,'conflicts.json'),sessions=new Map();await mkdir(DATA,{recursive:true});
const readJson=async(f,d)=>{try{return JSON.parse(await readFile(f,'utf8'))}catch{return d}};const writeJson=(f,x)=>writeFile(f,JSON.stringify(x,null,2));
function safe(p){const x=resolve(p);if(!x.startsWith('/mnt/'))throw Error('Paths must be under /mnt');return x}function json(r,s,b){r.writeHead(s,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-credentials':'true'});r.end(JSON.stringify(b))}async function body(q){let s='';for await(const c of q)s+=c;return s?JSON.parse(s):{}}
async function walk(root,dir=root,out=[]){for(const e of await readdir(dir,{withFileTypes:true})){const p=join(dir,e.name);if(e.isDirectory())await walk(root,p,out);else if(e.isFile())out.push(relative(root,p))}return out}
function run(a){return new Promise(ok=>{const p=spawn('rsync',a);let o='';p.stdout.on('data',d=>o+=d);p.stderr.on('data',d=>o+=d);p.on('close',code=>ok({code,out:o}))})}
async function truenasLogin(user,password){return await new Promise(resolve=>{const w=new WebSocket(TN_API_URL.replace(/^https:/,'wss:').replace(/\/api\/v2\.0$/,''),{rejectUnauthorized:false});let done=false;const finish=v=>{if(!done){done=true;try{w.close()}catch{};resolve(v)}};w.on('open',()=>{w.send(JSON.stringify({msg:'connect',version:'1',support:['1']}));});w.on('message',raw=>{let x;try{x=JSON.parse(raw)}catch{return}if(x.msg==='connected')w.send(JSON.stringify({id:1,msg:'method',method:'auth.login',params:[user,password]}));else if(x.id===1)finish(x.msg==='result'&&x.result===true)});w.on('error',()=>finish(false));setTimeout(()=>finish(false),10000)})}
function session(req){const m=(req.headers.cookie||'').match(/nas_session=([^;]+)/);return m&&sessions.get(m[1])}
async function conflicts(source,target,jobId){const a=await readJson(conflictsFile,[]),files=await walk(source);let changed=false;for(const rel of files){const sp=join(source,rel),dp=join(target,rel);if(!existsSync(dp))continue;const s=await stat(sp),d=await stat(dp);if(s.size===d.size&&Math.abs(s.mtimeMs-d.mtimeMs)<2000)continue;if(!a.some(x=>x.source===source&&x.target===target&&x.path===rel&&x.status!=='defer')){a.push({id:crypto.randomUUID(),jobId,source,target,path:rel,sourceSize:s.size,targetSize:d.size,sourceMtime:s.mtimeMs,targetMtime:d.mtimeMs,status:'pending'});changed=true}}if(changed)await writeJson(conflictsFile,a);return a.filter(x=>x.source===source&&x.target===target&&x.status==='pending').map(x=>x.path)}
async function copyJob(j){const pending=await conflicts(j.source,j.target,j.id),ex=join(DATA,`exclude-${j.id}.txt`);await writeFile(ex,pending.join('\n')+'\n');const r=await run(['-a','--partial','--append-verify','--ignore-existing','--stats','--exclude-from='+ex,j.source+'/',j.target+'/']);const h=await readJson(historyFile,[]),x=h.find(v=>v.id===j.id);Object.assign(x,{status:r.code===0?'completed':'failed',finished:new Date().toISOString(),exitCode:r.code,pendingConflicts:pending.length,output:r.out.slice(-20000)});await writeJson(historyFile,h)}
const server=createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PATCH,OPTIONS','access-control-allow-headers':'content-type,authorization','access-control-allow-credentials':'true'});return res.end()}if(u.pathname==='/health'&&req.method==='GET')return json(res,200,{status:'ok'});if(u.pathname==='/api/login'&&req.method==='POST'){const x=await body(req);if(!await truenasLogin(x.username,x.password))return json(res,401,{error:'invalid TrueNAS credentials'});const id=crypto.randomUUID();sessions.set(id,{username:x.username,at:Date.now()});res.writeHead(200,{'content-type':'application/json','set-cookie':`nas_session=${id}; HttpOnly; SameSite=Strict; Path=/`});return res.end(JSON.stringify({username:x.username}))}const logged=!!session(req), bearer=req.headers.authorization===`Bearer ${API_TOKEN}`;if(u.pathname.startsWith('/api')&&u.pathname!=='/api/login'&&!logged&&!bearer)return json(res,401,{error:'login required'});if(req.method==='GET'&&u.pathname==='/api/history')return json(res,200,await readJson(historyFile,[]));if(req.method==='GET'&&u.pathname==='/api/conflicts')return json(res,200,(await readJson(conflictsFile,[])).filter(x=>x.status==='pending'));if(req.method==='PATCH'&&u.pathname.startsWith('/api/conflicts/')){const id=u.pathname.split('/').pop(),x=await body(req),a=await readJson(conflictsFile,[]),c=a.find(v=>v.id===id);if(!c)return json(res,404,{error:'not found'});if(!['overwrite','accept','defer'].includes(x.decision))return json(res,400,{error:'invalid decision'});c.status=x.decision==='defer'?'pending':x.decision;c.decidedAt=new Date().toISOString();await writeJson(conflictsFile,a);if(x.decision==='overwrite'){const list=join(DATA,`one-${id}.list`);await writeFile(list,c.path+'\n');await run(['-a','--inplace','--files-from='+list,c.source+'/',c.target+'/'])}return json(res,200,c)}if(req.method==='POST'&&u.pathname==='/api/copy'){const x=await body(req),source=safe(x.source),target=safe(x.target);if(!existsSync(source))return json(res,400,{error:'source does not exist'});if(source===target||target.startsWith(source+'/'))return json(res,400,{error:'target must not be inside source'});const id=crypto.randomUUID(),h=await readJson(historyFile,[]);h.unshift({id,source,target,status:'running',started:new Date().toISOString(),options:'append-only; conflicts queued'});await writeJson(historyFile,h);copyJob({id,source,target});return json(res,202,{id})}if(req.method==='GET'){const f=u.pathname==='/'?'/index.html':u.pathname;try{const d=await readFile(join(process.cwd(),'public',f));res.writeHead(200,{'content-type':f.endsWith('.html')?'text/html; charset=utf-8':'text/plain'});return res.end(d)}catch{}}json(res,404,{error:'not found'})}catch(e){json(res,400,{error:e.message})}});server.listen(PORT,HOST,()=>console.log(`CleverNasUtility listening on ${HOST}:${PORT}`));
